#!/usr/bin/env bash
# inject-rules.sh
#
# Copia los rules de seguridad de ai-forge a un repo nuevo.
# Lo invoca el workflow scaffold.yml después de crear el repo.
#
# Uso:
#   bash inject-rules.sh <owner>/<repo>
#
# Pre-requisitos:
#   - GH_TOKEN exportado (con permisos write al repo destino)
#   - Estar parado en la raíz del ai-forge (necesita acceso a rules/)

set -euo pipefail

TARGET_REPO="${1:?Falta el repo destino. Uso: inject-rules.sh <owner>/<repo>}"
RULES_DIR="rules"
WORK_DIR=$(mktemp -d)

echo "🔨 Injecting rules into $TARGET_REPO"

# Clone temporal del repo destino
cd "$WORK_DIR"
gh repo clone "$TARGET_REPO" target -- --depth=1
cd target

# Crear .claude/rules/ si no existe
mkdir -p .claude/rules

# Copiar SKILL.md como entry point + todos los references
cp "$GITHUB_WORKSPACE/$RULES_DIR/SKILL.md" .claude/rules/SKILL.md
cp -r "$GITHUB_WORKSPACE/$RULES_DIR/references/"* .claude/rules/

# Agregar un README dentro de .claude/rules/ explicando qué son
cat > .claude/rules/README.md <<'EOF'
# Security Rules — Claude Code

Esta carpeta contiene las reglas de seguridad de Cashea que Claude Code carga
automáticamente al iniciar sesión en este repo.

**No las modifiques directamente acá.** La fuente de verdad vive en
[ai-forge](https://github.com/cashea-bnpl/ai-forge). Los updates se propagan
automáticamente via el workflow `publish-rules.yml` de ese repo.

## ¿Cómo funcionan?

Cuando arrancás Claude Code en este repo, lee todos los archivos en `.claude/rules/`
y los inyecta como el primer mensaje del modelo. Eso garantiza que las reglas
aplican a TODO lo que generes, sin que tengas que invocarlas.

## ¿Qué incluyen?

- `SKILL.md`: 12 reglas universales (secrets, auth, validation, errors, queries, logging, deps, data, headers, AI rules, detección de datos sensibles en prompts)
- `references/`: 9 referencias por dominio (auth, input-validation, data-security, logging, docker, iac-terraform, node-nestjs, python, frontend)

## ¿Y si tengo dudas?

- Slack: #appsec
- Email: security@cashea.app
- Notion: AI Security workspace
EOF

# Commit y push
git config user.name "Cashea AI Forge"
git config user.email "ai-forge@cashea.app"
git add .claude/rules/
git commit -m "chore(security): inject Cashea security rules from ai-forge

Auto-generated by ai-forge scaffolding. These rules are loaded
automatically by Claude Code when starting a session in this repo.

Source of truth: https://github.com/cashea-bnpl/ai-forge
"
git push origin HEAD

echo "✅ Rules injected into $TARGET_REPO"

# Cleanup
cd "$GITHUB_WORKSPACE"
rm -rf "$WORK_DIR"
